### ISSUE TITLE
请问限速假名的参数是如何选择的呢？

### ISSUE THREAD

**Issue by WystanW** [SecureCats/Evaluation_BackEnd#6]
看了论文之后，发现您关于假名的所有公共参数是固定的，这里面

哈希函数是

`function hash(val) {
  return new BigInteger(SHA256(val.toString()).toString(), 16).mod(
    new BigInteger('731499577')
  )
}`

请问731499577这个数字是如何生成的呢？

**Comment by richard008** [comment]
你好，请问一下你是怎么pipenv install成功的？肉身翻墙？

**Comment by richard008** [comment]
N:\SRC\Evaluation_BackEnd-master>pipenv install
Installing dependencies from Pipfile.lock (f8b465)…
An error occurred while installing gmpy2==2.0.8 --hash=sha256:288510251de747ac26c378ff5c1ebc9468323c10e511f470a41847d4ecd05f54 --hash=sha256:2e576baad2ee059a38f9c0a79c2857c22c8d084765ee2fcc826aff43f9edcb65 --hash=sha256:92f980c4bf5035e1eea4634817ec8a9a8d5b541bbec9f1a41fd4bb405b1bb81c --hash=sha256:9b53e8da0bcac6fbd509bc6a9174730e00ec8eaf43a5e43154985736bdae4b1f --hash=sha256:db4b58b5b2455118bf3fa56b8fcc82e4ef1b138a6b81f92ca7ef6f2f88711131 --hash=sha256:dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f --hash=sha256:e70435412e605f0c685b5ab524b969f3fdcdf076d6116290ad8d1329cfded496 --hash=sha256:fc116f425cc44b9b3835173ba5607be3c5a5093d23b25a6e0b2b1c42177fcc75 --hash=sha256:fc959314c8a378c927e2b7a41baccf8ad2a9fcf5c7afe06a84a4a47253ed7060! Will try again.
  ================================ 12/12 - 00:00:16
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "m:\program files\python37\lib\site-packages\pipenv\core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "m:\program files\python37\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "m:\program files\python37\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "m:\program files\python37\lib\site-packages\pipenv\core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "m:\program files\python37\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/', 'Collecting gmpy2==2.0.8', '  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/90/f4/9a2e384b325b69bc5827b9a6510a8fb4a51698c915c06a3f25a86458892a/gmpy2-2.0.8.zip (280 kB)', 'Building wheels for collected packages: gmpy2', '  Building wheel for gmpy2 (setup.py): started', "  Building wheel for gmpy2 (setup.py): finished with status 'error'", '  Running setup.py clean for gmpy2', 'Failed to build gmpy2', 'Installing collected packages: gmpy2', '    Running setup.py install for gmpy2: started', "    Running setup.py install for gmpy2: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', '   command: \'N:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\Scripts\\python.exe\' -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d \'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-wheel-b3ssa6w3\'', '       cwd: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-9ytrekv4\\gmpy2\\', '  Complete output (12 lines):', '  running bdist_wheel', '  running build', '  running build_ext', "  building 'gmpy2' extension", '  creating build', '  creating build\\temp.win-amd64-3.7', '  creating build\\temp.win-amd64-3.7\\Release', '  creating build\\temp.win-amd64-3.7\\Release\\src', '  M:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMPIR -DWITHMPFR -DWITHMPC -IN:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\include "-Im:\\program files\\python37\\include" "-Im:\\program files\\python37\\include" "-IM:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\ATLMFC\\include" "-IM:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\include" "-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt" /Tcsrc\\gmpy2.c /Fobuild\\temp.win-amd64-3.7\\Release\\src\\gmpy2.obj', '  gmpy2.c', '  C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-9ytrekv4\\gmpy2\\src\\gmpy.h(104): fatal error C1083: 无法打开包 括文件: “mpir.h”: No such file or directory', "  error: command 'M:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.24.28314\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit status 2", '  ----------------------------------------', '  ERROR: Failed building wheel for gmpy2', '    ERROR: Command errored out with exit status 1:', '     command: \'N:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\Scripts\\python.exe\' -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record \'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-record-bcmxxof4\\install-record.txt\' --single-version-externally-managed --compile --install-headers \'N:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\include\\site\\python3.7\\gmpy2\'', '         cwd: C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-9ytrekv4\\gmpy2\\', '    Complete output (12 lines):', '    running install', '    running build', '    running build_ext', "    building 'gmpy2' extension", '    creating build', '    creating build\\temp.win-amd64-3.7', '    creating build\\temp.win-amd64-3.7\\Release', '    creating build\\temp.win-amd64-3.7\\Release\\src', '    M:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DMPIR -DWITHMPFR -DWITHMPC -IN:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\include "-Im:\\program files\\python37\\include" "-Im:\\program files\\python37\\include" "-IM:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\ATLMFC\\include" "-IM:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\include" "-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt" "-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt" /Tcsrc\\gmpy2.c /Fobuild\\temp.win-amd64-3.7\\Release\\src\\gmpy2.obj', '    gmpy2.c', '    C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-9ytrekv4\\gmpy2\\src\\gmpy.h(104): fatal error C1083: 无法打开包括文件: “mpir.h”: No such file or directory', "    error: command 'M:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.24.28314\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit status 2", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: \'N:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\Scripts\\python.exe\' -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\'; __file__=\'"\'"\'C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\pip-install-9ytrekv4\\\\gmpy2\\\\setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record \'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-record-bcmxxof4\\install-record.txt\' --single-version-externally-managed --compile --install-headers \'N:\\envs\\Evaluation_BackEnd-master-OXXT3rIS\\include\\site\\python3.7\\gmpy2\' Check the logs for full command output.']
ERROR: ERROR: Package installation failed...
     ================================ 0/1 - 00:00:12

必出啊，WIN7的系统，python3.7的环境

**Comment by spencerwooo** [comment]
> 看了论文之后，发现您关于假名的所有公共参数是固定的，这里面
> 
> 哈希函数是
> 
> `function hash(val) { return new BigInteger(SHA256(val.toString()).toString(), 16).mod( new BigInteger('731499577') ) }`
> 
> 请问731499577这个数字是如何生成的呢？

是 @felinae98 当初随便编的。
